apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: external-bedbug-java-quarkus
  janus-idp.io/tekton: external-bedbug-java-quarkus
  backstage.io/kubernetes-id: external-bedbug-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-e2e 
  app.kubernetes.io/part-of: external-bedbug-java-quarkus
resources: 
- deployment.yaml
- route.yaml
- service.yaml
